### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by jdegoes** [ocastastudios/docker-slamdata#1]
First, this looks awesome, thank you for creating this!

Second, I suggest we make the change so the build file will grab from Github and build the application from source code. That is the official way to build the project and will continue working indefinitely (the Github releases method works for now, but will not work in the future).

**Comment by ocasta** [comment]
Now building from the source tar file. Using the tar file rather than directly from the repo to make sure we the builds match releases

**Comment by jdegoes** [comment]
👍
