### ISSUE TITLE
run.sh path to quasar is invalid

### ISSUE THREAD

**Issue by zwessels** [ocastastudios/docker-slamdata#5]
If I do a pull of the latest docker image, the run.sh script has an entry:

java -jar /slamdata/quasar.jar --content-path /slamdata/public

However, when you look inside the docker container there is no quasar.jar under /slamdata. Rather it is in the root directory.

**Comment by ocasta** [comment]
Fixed in master

**Comment by zwessels** [comment]
Thanks!
